In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from matplotlib.pyplot import figure
from fuzzy import run_fuzzy_c_means, plot_points

In [10]:
from sklearn.cluster import KMeans
from fcmeans import FCM

In [11]:
dataframe = pd.read_csv("D:\\Logistic_code\\code\\vrp\\clustering\\fuzzy_c_mean\\data2.csv")

In [ ]:
dataframe


In [12]:
data = dataframe.to_numpy()

## Fuzzy Impl

In [ ]:
def supervised_fuzzy_c_mean_clustering(num_cluster:int, data:np.ndarray, capacity:int):
    """
        num_cluster: number of vehicles. Can be increased if demand exceeds capacity
        data: data point and demand. Shape: [K, 3] with K is number of data point. Each row is (lat, lon, demand)
        capacity : vehicle capacity
    """
    cluster_center, weight_matrix, cluster_labels = None, None, None
    flag = True
    while flag:
        print(f"---------------Starting clustering with {num_cluster} vehicles---------------")
        ## Clustering
        my_model = FCM(n_clusters=num_cluster, max_iter=500) 
        my_model.fit(data[:,:2]) 
        cluster_center = my_model.centers
        cluster_labels = my_model.predict(data[:,:2])
        # cluster_center, weight_matrix, cluster_labels = fuzzy_c_means_clustering(num_cluster, data[:,:2])
        ## Check demand in each clusters
        is_exceeds = False
        for i in range(num_cluster):
            demand = np.sum(data[cluster_labels == i][:,2:3])
            if demand > capacity:
                print(f"Demand exceed at cluster {i} ({demand} > {capacity}). Increaseing number of vehicle to 1")
                is_exceeds = True
                num_cluster = num_cluster + 1
                break
        if not is_exceeds:
            flag = False
            print(f"Finishing clustering with number of vehicles {num_cluster}")

    return cluster_center, weight_matrix, cluster_labels, num_cluster

In [ ]:
def supervised_k_mean_clustering(num_cluster:int, data:np.ndarray, capacity:int):
    """
        num_cluster: number of vehicles. Can be increased if demand exceeds capacity
        data: data point and demand. Shape: [K, 3] with K is number of data point. Each row is (lat, lon, demand)
        capacity : vehicle capacity
    """
    cluster_center, weight_matrix, cluster_labels = None, None, None
    flag = True
    while flag:
        print(f"---------------Starting clustering with {num_cluster} vehicles---------------")
        ## Clustering
        kmeans = KMeans(n_clusters=num_cluster, random_state=0, max_iter=1000).fit(data[:,:2]) 
        cluster_center = kmeans.cluster_centers_
        cluster_labels = kmeans.labels_
        # cluster_center, weight_matrix, cluster_labels = fuzzy_c_means_clustering(num_cluster, data[:,:2])
        ## Check demand in each clusters
        is_exceeds = False
        for i in range(num_cluster):
            demand = np.sum(data[cluster_labels == i][:,2:3])
            if demand > capacity:
                print(f"Demand exceed at cluster {i} ({demand} > {capacity}). Increaseing number of vehicle to 1")
                is_exceeds = True
                num_cluster = num_cluster + 1
                break
        if not is_exceeds:
            flag = False
            print(f"Finishing clustering with number of vehicles {num_cluster}")

    return cluster_center, weight_matrix, cluster_labels, num_cluster

In [ ]:
cluster_center, weight_matrix, cluster_labels, num_cluster = supervised_fuzzy_c_mean_clustering(10, data, 66)

In [ ]:
data

In [ ]:
cluster_2 = cluster_center[cluster_labels]

In [ ]:
a = np.array(
    [
        [3, 5],
        [6, 9],
        [10, 12],
        [15, 14]
    ]
)
b = np.array(
    [
        [1, 5],
        [2, 9],
        [18, 15],
        [13, 16]
    ]
)

In [ ]:
np.sqrt(np.sum((a - b) ** 2, axis= 1))

In [ ]:
cluster_labels

In [ ]:
cluster_center

In [ ]:
np.argwhere(cluster_labels == cluster_labels[5])

In [ ]:
cluster_labels[5]


In [ ]:
def plot_points(cluster_labels:np.ndarray, cluster_center:np.ndarray, data:np.ndarray):
    figure(figsize=(14, 12), dpi=80)
    cluster_label_unique_len = len(np.unique(cluster_labels))
    cluster_color = np.random.rand(cluster_label_unique_len, 3)  

    ## Plot point
    point_color = cluster_color[cluster_labels]
    for i in range(data.shape[0]):
        point = data[i]
        plt.scatter(point[0], point[1], marker="o", c=[point_color[i]])

     ## plot cluster center
    plt.scatter(cluster_center[:,0], cluster_center[:,1], marker="x", c=[[0,0,0]])

    plt.show()

In [ ]:
plot_points(cluster_labels, cluster_center, data[:,:2])


## Library testing

In [5]:
cluster_center, cluster_labels, num_cluster, distance_data = run_fuzzy_c_means(
        10, 
        data, 
        66
    )

---------------Starting clustering with 10 vehicles---------------
Demand exceed at cluster 2 (121 > 66). Increaseing number of vehicle to 1
---------------Starting clustering with 11 vehicles---------------
Demand exceed at cluster 0 (70 > 66). Increaseing number of vehicle to 1
---------------Starting clustering with 12 vehicles---------------
Demand exceed at cluster 0 (74 > 66). Increaseing number of vehicle to 1
---------------Starting clustering with 13 vehicles---------------
Demand exceed at cluster 4 (93 > 66). Increaseing number of vehicle to 1
---------------Starting clustering with 14 vehicles---------------
Demand exceed at cluster 0 (68 > 66). Increaseing number of vehicle to 1
---------------Starting clustering with 15 vehicles---------------
Demand exceed at cluster 8 (70 > 66). Increaseing number of vehicle to 1
---------------Starting clustering with 16 vehicles---------------
Demand exceed at cluster 8 (74 > 66). Increaseing number of vehicle to 1
---------------Star

In [7]:
cluster_center

array([[798.77086973, 180.56359097],
       [100.35272572, 687.76526519],
       [445.60993417, 939.6325991 ],
       [477.11926294, 829.04414848],
       [519.39464442, 476.38808861],
       [931.43240856,  23.43048323],
       [534.92156411, 229.7339974 ],
       [896.18676008, 304.82586246],
       [936.24021872, 679.33756531],
       [314.41340233, 326.00682674],
       [325.62550662, 679.93251236],
       [125.30487738, 914.21429889],
       [475.37295605, 702.54169278],
       [672.90386008, 686.77079726],
       [806.19188734, 493.68796857],
       [615.94957369, 573.38622828],
       [672.27226322,  93.31299545],
       [756.64315344, 955.69651641],
       [814.79323328, 684.66830228],
       [118.54621512, 143.27294769],
       [146.67072923, 502.17857282]])

In [8]:
cluster_labels

array([ 4, 14, 10, 15,  2, 13, 12,  5,  6,  2,  6, 13,  9,  0,  4, 17,  7,
       20, 12,  9,  8, 19, 11,  0,  3,  3, 17, 20, 20,  7, 10, 20, 14,  2,
       18, 16,  1,  5, 15, 20,  6,  9,  8,  1,  7, 18, 13,  6, 16,  4,  9,
       18,  9, 17,  9,  2,  3,  0,  9, 20, 11, 11,  6,  6,  1,  1, 17, 18,
        9, 12,  7, 10, 19, 16,  8, 19, 11, 13,  7, 14, 10,  5,  0, 11,  3,
       18, 16, 17, 19, 18,  7, 15,  8,  1,  5, 20, 19,  8, 17,  1,  6,  2,
        2,  3, 11, 14,  8,  0, 15, 12], dtype=int64)

In [6]:
distance_data

array([[ 500.        ,  500.        ,    0.        ,    4.        ,
          30.55608927],
       [ 740.        ,  442.        ,    8.        ,   14.        ,
          83.98221267],
       [ 261.        ,  710.        ,   10.        ,   10.        ,
          71.27769581],
       [ 578.        ,  522.        ,    8.        ,   15.        ,
          63.8804712 ],
       [ 482.        ,  914.        ,    5.        ,    2.        ,
          44.5114258 ],
       [ 628.        ,  644.        ,   10.        ,   13.        ,
          62.01369001],
       [ 551.        ,  651.        ,    5.        ,   12.        ,
          91.52046695],
       [ 828.        ,   54.        ,    9.        ,    5.        ,
         107.85526643],
       [ 541.        ,  270.        ,   10.        ,    6.        ,
          40.72220952],
       [ 450.        , 1000.        ,    6.        ,    2.        ,
          60.5268186 ],
       [ 521.        ,  127.        ,    5.        ,    6.        ,
         103